---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: localhost
  connection_type: local
  roles:
    - common
- name: configure and deploy the webservers and application code
  hosts: localhost
  remote_user: root
  roles:
    - web
- name: deploy MySQL and configure the databases
  hosts: dbservers
  connection_type: local
  roles:
    - db
